Use abstract model instead of default model because I get an error otherwise
Without this, I get:
RuntimeError: Model class location.models.Session doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.

If only I have this problem, feel free to revert